AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A Step Functions Workflow for parallel Human Approval Process

Parameters:
  Approver1SNSEmailAddress:
    Type: String
    Default: approver@example.com
    Description: Enter the email address that will receive review notifications.
  Approver2SNSEmailAddress:
    Type: String
    Default: approver@example.com
    Description: Enter the email address that will receive review notifications.
  Approver3SNSEmailAddress:
    Type: String
    Default: approver@example.com
    Description: Enter the email address that will receive review notifications.
  
Resources:
##########################################################################
#   STEP FUNCTION                                                        #
##########################################################################

  StateMachineParallelHumanAproval:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/StateMachine.asl.json
      DefinitionSubstitutions:
        Approver1SNS: !Ref Approver1SNS
        Approver2SNS: !Ref Approver2SNS
        Approver3SNS: !Ref Approver3SNS
       
      Role:
        Fn::GetAtt: [ StatesExecutionRole, Arn ]
      Type: STANDARD
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
        IncludeExecutionData: false
        Level: 'ALL'
      Policies:
        - SNSPublishMessagePolicy:
            Approver1SNS: !GetAtt Approver1SNS.TopicName
            Approver2SNS: !GetAtt Approver2SNS.TopicName
            Approver3SNS: !GetAtt Approver3SNS.TopicName



##########################################################################
#  SNS Topics                                                       #
##########################################################################
  Approver1SNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: 'Approver1SNS'
      Subscription:
        - Endpoint: !Ref Approver1SNSEmailAddress
          Protocol: email
  Approver2SNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: 'Approver2SNS'
      Subscription:
        - Endpoint: !Ref Approver2SNSEmailAddress
          Protocol: email
  Approver3SNS:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: 'Approver3SNS'
      Subscription:
        - Endpoint: !Ref Approver3SNSEmailAddress
          Protocol: email     

##########################################################################
#  STEP FUNCTION LOG GROUP                                               #
##########################################################################
  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join [ "/", [ "stepfunctions", StateMachineParallelHumanAproval]]
            
##########################################################################
#   Outputs                                                              #
##########################################################################
Outputs:
  StateMachineExpressSynctoLambda:
    Value: !Ref StateMachineExpressSynctoLambda
    Description: StateMachineExpressSynctoLambda Arn
